### Registration request
POST https://{{baseUrl}}/prod/register
Content-Type: application/json

{
    "email": "tcbenkhard@gmail.com",
    "password": "DitIsEenTest",
    "name": "Timo Benkhard"
}

### Login request
POST https://{{baseUrl}}/prod/login
Content-Type: application/json
Authorization: Basic tcbenkhard@gmail.com DitIsEenTest

### Invalid Login request
POST https://{{baseUrl}}/prod/login
Content-Type: application/json
Authorization: Basic tcbenkhard@gmail.com DitIsFout

### Maak een lijst
POST https://{{baseUrl}}/prod/lists
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzEwMjMwMzY3LCJleHAiOjE3MTAzMTY3NjcsInN1YiI6InRjYmVua2hhcmRAZ21haWwuY29tIn0.vXz_m102wOYqdBpX_tJsXr68OVhusHkMgd9rIz1iHu8

{
  "title": "Test lijst"
}

### Get my lists
GET https://{{baseUrl}}/prod/lists
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzEwMjMwMzY3LCJleHAiOjE3MTAzMTY3NjcsInN1YiI6InRjYmVua2hhcmRAZ21haWwuY29tIn0.vXz_m102wOYqdBpX_tJsXr68OVhusHkMgd9rIz1iHu8


### Create a task in a list
POST https://{{baseUrl}}/prod/lists/1371cc81-82cb-44b9-a198-e533a6b61a0e/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzEwMjMwMzY3LCJleHAiOjE3MTAzMTY3NjcsInN1YiI6InRjYmVua2hhcmRAZ21haWwuY29tIn0.vXz_m102wOYqdBpX_tJsXr68OVhusHkMgd9rIz1iHu8

{
  "title": "My Sixth Task",
  "description": "This is my very sixth task",
  "priority": 1,
  "type": "flexible",
  "schedule": {
    "interval": 1,
    "period": "weeks"
  },
  "startAt": "2024-02-23"
}

### Get list
GET https://{{baseUrl}}/prod/lists/1371cc81-82cb-44b9-a198-e533a6b61a0e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzEwMjMwMzY3LCJleHAiOjE3MTAzMTY3NjcsInN1YiI6InRjYmVua2hhcmRAZ21haWwuY29tIn0.vXz_m102wOYqdBpX_tJsXr68OVhusHkMgd9rIz1iHu8
